kind: pipeline
type: docker
name: Git插件


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 拉代码
    image: dronestock/git
    pull: always
    settings:
      verbose: true
      debug: true
      ssh_key:
        from_secret: ssh_key_github

  - name: 编译
    image: pangum/drone
    pull: always
    settings:
      verbose: true
      debug: true
      output: git

  - name: 推送Docker镜像到中央库
    image: dronestock/docker
    pull: always
    privileged: true
    settings:
      repository: dronestock/git
      username: dronestock
      password:
        from_secret: token_docker
