kind: pipeline
type: docker
name: Git


clone:
  disable: true


steps:
  - name: 代码
    image: dronestock/git

  - name: 编译
    image: pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      output: git

  - name: 发布
    image: dronestock/docker
    privileged: true
    volumes:
      - name: docker
        path: /var/lib/docker
    settings:
      repository: dronestock/git
      username: dronestock
      password:
        from_secret: token_docker


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
  - name: docker
    host:
      path: /var/lib/cache/docker
