kind: pipeline
type: docker
name: Git插件


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 拉代码
    image: dronestock/git
    pull: if-not-exists
    settings:
      verbose: true

  - name: 编译
    image: dronestock/pangu
    pull: if-not-exists
    settings:
      output: git

  - name: 推送Docker镜像到腾讯云
    image: ccr.ccs.tencentyun.com/dronestock/docker
    pull: always
    privileged: true
    settings:
      registry: ccr.ccs.tencentyun.com
      repository: dronestock/git
      username:
        from_secret: username_docker_tencentyun
      password:
        from_secret: password_docker_tencentyun

  - name: 推送Docker镜像到中央库
    image: ccr.ccs.tencentyun.com/dronestock/docker
    pull: if-not-exists
    failure: ignore
    privileged: true
    settings:
      repository: dronestock/git
      username:
        from_secret: username_docker
      password:
        from_secret: token_docker
